[game]
hostname = "☢️ S.T.A.L.K.E.R. ☢️ Debug."
desc = "In devlopment."

map = "STDev"
map_pool = "STDefaultMapPool"

map_rotation = false

lobbyenabled = false

maxplayers = 80
soft_max_players = 60

role_timers = true
peaceful_end = false
contraband_examine = false

[server]
default_guide = "STNewPlayer"
rules_file = "STRuleset"

[rules]
time = 10.0

[netres]
limit = 25

[whitelist]
enabled = false

[explosion]
can_create_vacuum = false

[tips]
enabled = false

[shuttle]
auto_call_time = 0
emergency = false
arrivals = false
preload_grids = false
camera_rotation_locked = true

[ic]
flavor_text = true
punctuation = false

[infolinks]
discord = "https://discord.gg/BuvKkKhrjn"
patreon = "https://boosty.to/stalkerss14"

[hub]
advertise = false
tags = "lang:ru,lang:en,rp:medium,region:eu_e"
hub_urls = "https://hub.spacestation14.com/"

[events]
enabled = false

[physics]
grid_splitting = false
maxlinvelocity = 72
target_minimum_tickrate = 120

[npc]
max_updates = 150

[net]
sendbuffersize = 393213
receivebuffersize = 393213
pvs_range = 25
tickrate = 30
max_buffer_size = 1024
log_late_msg = false

[crewmanifest]
no_entity = false
