- type: entity
  parent: STBaseWeapon
  id: STBaseWeaponGun
  name: A gun
  abstract: true
  components:
    # Allows guns to get effects from modules,
    # without this, YOU CAN add modules but NO EFFECT
    - type: STWeaponModuleContainer
    - type: STWeight
      self: 2.7
    - type: Clothing
      equipDelay: 1
      slots:
        - Back
        - SuitStorage
      quickEquip: false
    - type: AmmoCounter
    - type: Item
      size: Large
      shape:
        - 0,0,5,1
    - type: Sprite
      layers:
        - state: base
          map: ["enum.GunVisualLayers.Base"]
        - state: mag-0
          map: ["enum.GunVisualLayers.Mag"]
    # - type: ChamberMagazineAmmoProvider
    - type: ItemSlots
      # If you change the caliber,
      # you need to completely rewrite every property described here
      slots:
        gun_magazine:
          name: Magazine
          priority: 3
        # Here you have to customize your wunderwaffle modules,
        # you can put them on the gun initially through startingItem,
        # but remember if you change the containers,
        # you have to re-specify them all again
        gun_chamber:
          name: Chamber
          priority: 1
    - type: ContainerContainer
      containers:
        gun_magazine: !type:ContainerSlot
        gun_chamber: !type:ContainerSlot
      muzzleState: muzzle
    - type: Appearance
    - type: PullDoAfter
      pullTime: 2.5
    - type: Craftable
    - type: RepositoryItem
      categoryName: Weapon
