- type: job
  id: MilitaryStalker
  name: Военстал
  icon: voen
  description: Солдаты, прошедшие после опыта службы в Зоне специальную подготовку, или сталкеры, подписавшие контракт с армией.
  playTimeTracker: JobMilitaryStalker
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobMilitaryStalker
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitarySpecGear
  supervisors: Ты будешь терпеть и страдать, Victoria cruenta
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - MilitaryStalker
      - type: Bands
        altBand: stalker
        canChange: true
        band: Stalker
        bandIcon: voen
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3

- type: job
  id: Military
  name: Военный
  icon: army
  description: Удерживают Зону для предотвращения разграбления опасных радиоактивных материалов и предотвращения несанкционированного проникновения любых лиц.
  playTimeTracker: JobMilitary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobMilitary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGear
  supervisors: Вы подчиняетесь старшим по званию.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
      - type: Access
        groups:
          - Military
      - type: Bands
        band: Stalker
        bandIcon: army
      - type: BlockTackingHolyItems
      - type: TeethPull
        teethProto: ToothStalker
        pullingItemTag: PliersStalker
        teethCount: 3
        initialTeeth: 3


- type: job
  id: MilitaryHead
  name: Начальник Гарнизона
  icon: army
  description: Удерживают Зону для предотвращения разграбления опасных радиоактивных материалов и предотвращения несанкционированного проникновения любых лиц.
  playTimeTracker: JobHeadMilitary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobHeadMilitary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGearHead
  supervisors: Вы подчиняетесь старшим по званию.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - MilitaryHead
        - type: Bands
          band: Stalker
          bandIcon: army
        - type: BlockTackingHolyItems
        - type: TeethPull
          teethProto: ToothStalker
          pullingItemTag: PliersStalker
          teethCount: 3
          initialTeeth: 3

- type: job
  id: MilitaryOfficer
  name: Командир Военных
  icon: army
  description: Удерживают Зону для предотвращения разграбления опасных радиоактивных материалов и предотвращения несанкционированного проникновения любых лиц.
  playTimeTracker: JobOfficerMilitary
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobOfficerMilitary
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: MilitaryGearOfficer
  supervisors: Вы подчиняетесь старшим по званию.
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          groups:
            - MilitaryOfficer
        - type: Bands
          band: Stalker
          bandIcon: army
        - type: BlockTackingHolyItems

- type: startingGear
  id: MilitaryGear
  equipment:
    legs: ClothingLegsBoxersMilitary
    torso: ClothingTorsoTankMilitary
    shoes: ClothingShoesPortyanki

- type: startingGear
  id: MilitaryGearOfficer
  equipment:
    legs: ClothingLegsBoxersMilitary
    torso: ClothingTorsoTankMilitary
    shoes: ClothingShoesPortyanki

- type: startingGear
  id: MilitaryGearHead
  equipment:
    id: MilitaryPDA
    legs: ClothingLegsBoxersMilitary
    torso: ClothingTorsoTankMilitary
    shoes: ClothingShoesPortyanki

- type: startingGear
  id: MilitarySpecGear
  equipment:
    id: MilitaryPDA
    belt: ClothingBeltStorageWaistbag
    legs: ClothingLegsJeansGreenCargo
    torso: ClothingTorsoTurtlenecksMilitary
    shoes: ClothingShoesBootsCombatFilled
