- type: job
  id: StalkerRene
  name: job-renegade
  icon: rene
  description: job-renegade-desc
  playTimeTracker: JobRenegat
  whitelisted: true
  requirements:
    # - !type:RoleTimeRequirement
    #   role: JobRenegat
    #   time: 1
    - !type:SpeciesRequirement
      species:
      - Human
      - Dwarf
  startingGear: ReneGear
  supervisors: job-renegade-supervisor
  canBeAntag: false
  special:
    - !type:AddComponentSpecial
      components:
        - type: Access
          tags:
            - Renegat
        - type: Bands
          band: Stalker
          bandIcon: rene
        - type: BlockTackingHolyItems

- type: startingGear
  id: ReneGear
  equipment:
    id: BandPDA
    belt: ClothingBeltStorageWaistbag
    head: ClothingHeadHatGreyFlatcap
    torso: ClothingTorsoTShirtColorBlack
    legs: ClothingLegsJeansBlue
    shoes: ClothingShoesBootsWork
